[2025-03-13T06:24:40.286+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-13T06:24:40.335+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_prep_transformation.data_validation manual__2025-03-13T05:47:39.846529+00:00 [queued]>
[2025-03-13T06:24:40.365+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_prep_transformation.data_validation manual__2025-03-13T05:47:39.846529+00:00 [queued]>
[2025-03-13T06:24:40.367+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 4
[2025-03-13T06:24:40.458+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): data_validation> on 2025-03-13 05:47:39.846529+00:00
[2025-03-13T06:24:40.656+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_prep_transformation', 'data_validation', 'manual__2025-03-13T05:47:39.846529+00:00', '--job-id', '231', '--raw', '--subdir', 'DAGS_FOLDER/data_prep_transformation.py', '--cfg-path', '/tmp/tmpcgm6wd0x']
[2025-03-13T06:24:40.698+0000] {standard_task_runner.py:105} INFO - Job 231: Subtask data_validation
[2025-03-13T06:24:40.709+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=100) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-13T06:24:40.713+0000] {standard_task_runner.py:72} INFO - Started process 118 to run task
[2025-03-13T06:24:41.467+0000] {task_command.py:467} INFO - Running <TaskInstance: data_prep_transformation.data_validation manual__2025-03-13T05:47:39.846529+00:00 [running]> on host 0aec637a790b
[2025-03-13T06:24:42.590+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_prep_transformation' AIRFLOW_CTX_TASK_ID='data_validation' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T05:47:39.846529+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-13T05:47:39.846529+00:00'
[2025-03-13T06:24:42.634+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-13T06:24:43.633+0000] {logging_mixin.py:190} INFO - Data Validation Completed. Report saved at:
[2025-03-13T06:24:43.634+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-13T06:24:43.666+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-13T06:24:43.668+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=data_prep_transformation, task_id=data_validation, run_id=manual__2025-03-13T05:47:39.846529+00:00, execution_date=20250313T054739, start_date=20250313T062440, end_date=20250313T062443
[2025-03-13T06:24:43.871+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-13T06:24:43.985+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-13T06:24:44.017+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
